### ISSUE TITLE
Unable to generate Attestation on a Standard_DC4as_v5 VM in AKS

### ISSUE THREAD

**Issue by sid-habu** [microsoft/archived-confidential-sidecar-containers#13]
This client generates a [local RSA private key](https://github.com/microsoft/confidential-sidecar-containers/blob/main/pkg/skr/skr.go#L53) and uses the public key to wrap the response from AKV. We tried invoking the [Secure Key Release API](https://github.com/microsoft/confidential-sidecar-containers/blob/main/cmd/skr/main.go#L163) that internally generates a quote, gets it attested and then uses the MAA token to do secure key release

However, this client was unable to generate an MAA token as it wasn’t able to find PSP device plugin dev/sev on a Standard_DC4as_v5 VM attached to the AKS cluster

```
{"error":"fetching snp report failed: cmd.Run() for fetching snp report failed: fork/exec /bin/get-fake-snp-report: no such file or directory"}
```

We also tried running the get-snp-report command directly on the VM and found the same error

```
/bin # get-snp-report
Failed to open /dev/sev
```

**Comment by KenGordon** [comment]
This repository is for sidecars that provide secure key release and related functionality in a confidential containers environment. It uses the PSP interface provided by that environment. I am not sure which OS you are using on the DC4as_v5 VM so can't help with how to get an attestation report there.

If you ping me an email I might be able to direct you to someone who can help.

**Comment by sid-habu** [comment]
@KenGordon thanks, we can connect at sharmasiddharth@hotmail.com

I will give you some background of the work we are doing with the ACC team
