### ISSUE TITLE
importkey tool - running from Devops - pulling mhsm response body failed: http response status equal to 401 Unauthorized

### ISSUE THREAD

**Issue by syambabu8k** [microsoft/archived-confidential-sidecar-containers#7]
Trying to run importkey from Devops pipeline, but we are unsuccessful. we are getting the following error.

pulling mhsm response body failed: http response status equal to 401 Unauthorized

when we use importkey from my laptop using same importkeyconfig.json file which is generated from Devops pipeline which include Bearer token is working without any errors.

Sample Devops Code:

- task: AzureCLI@2
    displayName: "Golang ImportKey"
    inputs:
      azureSubscription: $(servicename)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription $(subscription_id)
        token=$(az account get-access-token --resource https://managedhsm.azure.net | jq -r ".accessToken")
        export GOPATH=`pwd`/go
        go install github.com/Microsoft/confidential-sidecar-containers/cmd/...@latest
        go install github.com/Microsoft/confidential-sidecar-containers/tools/importkey/...@latest
        decodedConfig=`echo $(importconfig) | base64 -d`
        echo "${decodedConfig}" >importconfig.json
        sed -e 's/<<bearertoken>>/'$token'/' importconfig.json
        $GOPATH/bin/importkey -c importconfig.json -kh xxxxxx

Error Message:
importkey -c importconfig.json -kh xxxxxxxxxx
[68 149 211 98 46 41 150 106 86 248 193 87 10 45 154 74 97 52 65 201 52 19 91 88 196 184 239 209 67 82 21 2]
pulling mhsm response body failed: http response status equal to 401 Unauthorized

**Comment by svolos** [comment]
Has this issue been resolved?

**Comment by svolos** [comment]
Closing this issue as there has not been response from the issuer. The importkey tool has been successfully utilized to import keys when passing a Bearer Token or if run within Azure.
